#+AUTHOR: W
#+SETUPFILE: /Users/whkoh/git-repos/org-html-themes/org/theme-readtheorg-local-parent.setup
#+TITLE: No BS Guide to Linear Algebra
* Chapter 1: Math Fundamentals
** Completing the square
- Rewrite any quadratic expression $x^2 + BX + C$ as perfect square + some correction factor, i.e. $(x+p)^2 + k$.
- Becomes: $x^2 + Bx + C = (x+\frac{B}{2})^2 + C - (\frac{B}{2})^2$
** Quadratic formula
- $x = \frac{-b\pm \sqrt{b^2-4ac}}{2a}$
- Discriminant: $b^2-4ac$
** Golden ratio
- $x^2-x-1=0$
- $x_1 = (1+\sqrt(5))/2 = \phi$
- $x_2 = (1-\sqrt(5))/2 = -1/\phi$
** Solving systems of linear equations
- Examples
  - $n=1$ : $2x+4=7x$
  - $n=2$ : $x+2y=5$ $3x+9y=21$
- Principles: with $n$ equations and $n$ unknowns, the equations can be solved simultaneously:
  1. By substitution, i.e. isolate $x$ in eq1 to obtain $x=5-2y$, then substitute $x$ into eq2:
     $3(5-2y) + 9y = 21$, then expand to $15-6y+9y=21; 3y=6; y=2$
  2. By subtraction, i.e. multiply eq1 by 3 to obtain: $3x+6y=15 \& 3x+9y=21$, then gets $3y=6$ as the $3x$ terms cancel.
  3. By equating, i.e. isolate $x$ in both eq1 and eq2, then equate them. $x=5-2y; x=\frac{1}{3}(21-9y) = 7-3y$
More advanced techniques will be covered in chapter 3.
*** Geometric solution
Solving system of 2 linear equations in 2 unknowns is equivalent geometrically to finding the point of intersection between 2 lines in the Cartesian plane.
$ax+by=c$ with unknown $x, y$ is actually a *constraint* equation on the set of possible values for $x, y$.
Visualize this by considering the coordinate pairs $(x,y)$ that lie in the Cartesian plane.
Cartesian plane as a whole corresponds to the set $\mathbb{R}^2$ which describes all possible pairs of coordinates.

More precisely:
$$
l : \{(x,y) \in \mathbb{R}^2 | ax+by=c\}
$$

i.e.: line $l$ is defined as the subset of pairs of real numbers $(x,y)$ that satisfy equation $ax+by=c$.

Hence, the geometric approach is to:
1. draw the lines that correspond to each of the equations
2. Find the coordinates of the point where both lines intersect
*** Set notation
And its use in defining possible cases when solving system of 2 linear equations in 2 unknowns
**** One solution
Lines $l_1$ and $l_2$ are non-parallel and intersect at a point.
$$
\{(x,y \in \mathbb{R}^2 | x + 2y=2)\} \cap \{(x,y) \in \mathbb{R}^2 | x=1\} = \{(1, \frac{1}{2})\}
$$
**** No solution
Lines $l_1$ and $l_2$ are parallel and never intersect.
$$
\{(x,y \in \mathbb{R}^2 | x + 2y=2)\} \cap \{(x,y) \in \mathbb{R}^2 | x+2y=4\} = \emptyset
$$
**** Infinitely many solutions
If the lines $l_1$ and $l_2$ are parallel and overlapping.
*** Conclusion
The solution set can be a point, the empty set or a line.
* Chapter 2: Intro to Linear Algebra
Definitions and basic operations
** Vector operations
1. Addition $+$
2. Subtraction $-$
3. Scaling (implicit)
4. Dot product ($\cdot$)
5. Cross product ($\times$)
** Matrix operations
1. Addition ($A + B$)
2. Subtraction ($A-B$)
3. Scaling by a constant $\alpha$ ($\alpha A$)
4. Matrix product ($AB$)
5. Matrix-vector product ($A \vec{v}$)
6. Matrix inverse ($A^{-1}$)
7. Trace $Tr(A)$
8. Determinant ($det(A)$)
** Matrix-vector product
For matrix $A \in \mathbb{R}^{m\times n}$ and the vector $\vec{v}\in \mathbb{R}^n$.

Matrix-vector product $A \vec{x}$ produces a linear combination of the columns of matrix $A$ with coefficients $\vec{x}$.

E.g.: $\vec{y} = A \vec{x}$

*** Dual interpretation of matrix-vector product
- Row picture: single vector with all operations in them. Compute the dot product of the vector with each of the rows of matrix $A$
- Column picture: multiply each cell of the vector with each column of the matrix. _i.e._, $\vec{y}$ is a linear combination of the columns of $A$.

*** Linear combinations as matrix products
